version: "3"

services:
  api:
    build:
      context: ./api
      target: dev
    container_name: api
    volumes:
     - ./api:/api:cached
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    networks:
     - db_network
     - api_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`, `e1r8p3.42.fr`) && PathPrefix(`/api/`, `/socket.io/`, `/docs`, `/public/`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.docker.network=ft_transcendence_api_network"
    restart: on-failure:3

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: frontend
    volumes:
     - ./frontend:/frontend:cached
    environment:
      - NODE_ENV=development
      - FAST_REFRESH=true
    env_file:
      - ./.env
    networks:
     - api_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`, `e1r8p3.42.fr`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=ft_transcendence_api_network"
    restart: on-failure:3

  traefik:
    image: "traefik:vacherin"
    container_name: "traefik"
    networks:
      - api_network
    command:
      - "--log.level=ERROR"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
      - "9090:8080"
    volumes:
      - "${DOCKER_SOCK}:/var/run/docker.sock:ro"

  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    env_file:
      - ./.env
    networks:
     - db_network
    volumes:
     - /var/lib/postgresql

##
# DEBUG CONTAINERS --profile debug
##
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    networks:
      - db_network
    volumes:
      - ${PGADMIN_PATH}:/var/lib/pgadmin
    ports:
      - "5050:80"
    profiles:
      - debug

networks:
  db_network:
  api_network:
